<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="usecases\commands\**" />
    <Compile Remove="usecases\queries\**" />
    <EmbeddedResource Remove="usecases\commands\**" />
    <EmbeddedResource Remove="usecases\queries\**" />
    <None Remove="usecases\commands\**" />
    <None Remove="usecases\queries\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.6.0" />
    <PackageReference Include="FirebaseAdmin" Version="3.6.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Google.Apis.Auth" Version="1.76.0" />
    <PackageReference Include="Google.Apis.Drive.v3" Version="1.76.0.4261" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.9" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Journey_of_faith.Domain\Journey_of_faith.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="common\dtos\" />
    <Folder Include="usecases\auth\commands\NewFolder\" />
    <Folder Include="usecases\auth\dtos\" />
  </ItemGroup>

</Project>
